# Offense count: 17
Metrics/AbcSize:
  Max: 51

# Offense count: 3
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 3
Style/ModuleFunction:
  Enabled: false
