# Offense count: 14
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 14
Lint/UselessAssignment:
  Enabled: false

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 281
# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 158

# Offense count: 29
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 30

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 8

# Offense count: 3
Style/AccessorMethodName:
  Enabled: false

# Offense count: 5
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 14
Style/Documentation:
  Enabled: false

# Offense count: 59
# Configuration parameters: Exclude.
Style/FileName:
  Enabled: false

# Offense count: 3
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 397
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Offense count: 50
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 3
Style/ModuleFunction:
  Enabled: false

# Offense count: 4
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Offense count: 3
# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: false

# Offense count: 39
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 4261
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
Style/WordArray:
  MinSize: 4
