AllCops:
  Exclude:
    - 'build-essential/**/*'
    - 'chef_handler/**/*'
    - 'chef_handler_sns/**/*'
    - 'cron/**/*'
    - 'xml/**/*'
    - 'python/**/*'
    - 'ohai/**/*'
    - 'opsworks_nodejs/**/*'
    - 'vagrant-test/**/*'
    - 'test/**/*'

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

inherit_from: .rubocop_todo.yml