# Offense count: 19
Metrics/AbcSize:
  Max: 51

# Offense count: 23
# Cop supports --auto-correct.
Style/ClosingParenthesisIndentation:
  Enabled: false

# Offense count: 114
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FirstParameterIndentation:
  Enabled: false

# Offense count: 9
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 4
Style/ModuleFunction:
  Enabled: false
