# Offense count: 19
Metrics/AbcSize:
  Max: 51

# Offense count: 9
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 4
Style/ModuleFunction:
  Enabled: false
